import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { EchoProvider } from "./providers/EchoProvider";
=======
>>>>>>> 96e82ab49773b88e6a3cf4cd99f099d25afca2e2

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Tic Tac Toc Game",
  description: "Generated by create next",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 96e82ab49773b88e6a3cf4cd99f099d25afca2e2
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<<<<<<< HEAD
      <body className="min-h-full flex flex-col">
         <EchoProvider>
           {children}

         </EchoProvider>
       
      
        </body>
=======
      <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> 96e82ab49773b88e6a3cf4cd99f099d25afca2e2
    </html>
  );
}
